dist: trusty
sudo: required
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "nightly"
before_install:
  - sudo apt-get update -qq
  - sudo pip install -U pip
install: "pip install -r requirements_dev.txt"
script: make test
